spring:
  sql:
    show: true
    format: true
  application:
    name: databaseWork
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=HospitalManagementSystem;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456

jakarta.persistence:
  jdbc:
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=HospitalManagementSystem;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123